[book]
authors = ["Zola Gonano"]
language = "en"
multilingual = false
src = "src"
title = "A Ninja's Handbook"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
git-repository-url = "https://github.com/zolagonano/a-ninjas-handbook"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
