[book]
authors = ["Zola Gonano", "Navid Kashani"]
language = "fa"
multilingual = false
src = "src"
title = "کتابچه راهنمای یک نینجا"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
git-repository-url = "https://github.com/navidkashani/a-ninjas-handbook"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]